/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ImageFilter {
        "alt": string;
        "class": string;
        "filter": string;
        "height": string;
        "src": string;
        "width": string;
    }
}
declare global {
    interface HTMLImageFilterElement extends Components.ImageFilter, HTMLStencilElement {
    }
    var HTMLImageFilterElement: {
        prototype: HTMLImageFilterElement;
        new (): HTMLImageFilterElement;
    };
    interface HTMLElementTagNameMap {
        "image-filter": HTMLImageFilterElement;
    }
}
declare namespace LocalJSX {
    interface ImageFilter {
        "alt"?: string;
        "class"?: string;
        "filter"?: string;
        "height"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "image-filter": ImageFilter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "image-filter": LocalJSX.ImageFilter & JSXBase.HTMLAttributes<HTMLImageFilterElement>;
        }
    }
}
